### ISSUE TITLE
api keys

### ISSUE THREAD

**Issue by BajanPro** [carey5/BestBuyCA_Item_Avail#1]
hi - you have your api keys and phone number publicly available!

If you want to collab on a private repo I am working on for bestbuy auto checkout hit me up on twitter @bajanpro

**Comment by carey5** [comment]
Thanks, deleted the keys. Phone number was 514-420-6969 i hope i had it!

**Comment by BajanPro** [comment]
you should delete it from the file history also - 

https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#:~:text=If%20you%20commit%20sensitive%20data,Repo%2DCleaner%20open%20source%20tool.

**Comment by carey5** [comment]
great just learned something new
